export const SET_NODE_MAP = "SET_NODE_MAP";
export const UPDATE_NODE_STATUS = "UPDATE_NODE_STATUS";
export const START_MULTI_SELECTING = "START_MULTI_SELECTING";
export const STOP_MULTI_SELECTING = "STOP_MULTI_SELECTING";
export const RESET_NODE_STATUS = "RESET_NODE_STATUS";